services:
    backend:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: backend_taskme
        restart: unless-stopped
        working_dir: /var/www/app
        volumes:
            - .:/var/www/app
        depends_on:
            database:
                condition: service_healthy
            memcached:
                condition: service_started
        networks:
            - network_taskme
        command: sh -c "php artisan migrate --force && php-fpm"

    database:
        image: mysql:latest
        container_name: database_taskme
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            -   target: 3306
                published: 3306
                protocol: tcp
        networks:
            - network_taskme
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            retries: 5
            timeout: 5s

    memcached:
        image: memcached:latest
        container_name: memcached_taskme
        restart: unless-stopped
        networks:
            - network_taskme

    nginx:
        image: nginx:latest
        container_name: nginx_taskme
        restart: unless-stopped
        ports:
            - "9090:9090"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend
        networks:
            - network_taskme

    swagger-ui:
        image: swaggerapi/swagger-ui
        ports:
            - "8080:8080"
        networks:
            - network_taskme
        environment:
            SWAGGER_JSON_URL: "/docs/openapi.yaml"
        volumes:
            - ./docs/openapi.yaml:/usr/share/nginx/html/docs/openapi.yaml

networks:
    network_taskme:
        driver: bridge
